# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr = np.array([1,1])
arr
# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,1],[2,2]])
arr2

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1,1],
                 [5,5],
                 [7,7]],
                [[4,4],
                 [2,2],
                 [8,8]]])
arr3.shape

(2, 3, 2)

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr.shape
arr.ndim
arr.dtype
arr3.size
arr3.shape

(2, 3, 2)

In [4]:
# Attributes of 2-dimensional array
arr2.T

array([[1, 2],
       [1, 2]])

In [5]:
# Attributes of 3-dimensional array
arr3.T

array([[[1, 4],
        [5, 2],
        [7, 8]],

       [[1, 4],
        [5, 2],
        [7, 8]]])

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df = pd.DataFrame(arr2)
df

,0,1
0,1,1
1,2,2


In [7]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10,2))
ones_arr


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
r = np.arange(0,100,3)
r

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr = np.random.randint(0,10,(7,2))
random_arr

array([[2, 6],
       [4, 7],
       [3, 8],
       [9, 2],
       [3, 4],
       [6, 5],
       [1, 2]], dtype=int32)

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rand_arr = np.random.random((3,5))
rand_arr

array([[0.03620592, 0.682323  , 0.6282307 , 0.40532218, 0.65228245],
       [0.77769086, 0.00618567, 0.5170068 , 0.64977493, 0.79108923],
       [0.52386136, 0.27097577, 0.10387118, 0.59308422, 0.19879878]])

In [12]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
rand_arr_2 = np.random.randint(0,10,(4,6))
rand_arr_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]], dtype=int32)

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
rand_arr_3 = np.random.randint(0,10,(3,7))
rand_arr_3
# Find the unique numbers in the array you just created
rand_arr_3, np.unique(rand_arr_3)

(array([[8, 0, 9, 2, 6, 3, 8],
        [2, 4, 2, 6, 4, 8, 6],
        [1, 3, 8, 1, 9, 8, 9]], dtype=int32),
 array([0, 1, 2, 3, 4, 6, 8, 9], dtype=int32))

In [14]:
# Find the 0'th index of the latest array you created
rand_arr_3[0]

array([8, 0, 9, 2, 6, 3, 8], dtype=int32)

In [15]:
# Get the first 2 rows of latest array you created
rand_arr_3[0:2,:]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]], dtype=int32)

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
rand_arr_3[0:2,0:2]

array([[8, 0],
       [2, 4]], dtype=int32)

In [17]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
r_a_4 = np.random.randint(0,10, (3,5))
ones = np.ones((3,5))

In [18]:
# Add the two arrays together
r_a_4 + ones

array([[ 5.,  2.,  4.,  7.,  8.],
       [ 3.,  1.,  4.,  2.,  8.],
       [ 4.,  2.,  6.,  6., 10.]])

In [19]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones((5,3))

In [20]:
# Try add the array of ones and the other most recent array together
ones_2 = ones_2.reshape(3,5)
r_a_4 + ones + ones_2

array([[ 6.,  3.,  5.,  8.,  9.],
       [ 4.,  2.,  5.,  3.,  9.],
       [ 5.,  3.,  7.,  7., 11.]])

In [21]:
# Create another array of ones of shape (3, 5)
ones = np.ones((3,5))

In [22]:
# Subtract the new array of ones from the other most recent array
r_a_4 + ones + ones

array([[ 6.,  3.,  5.,  8.,  9.],
       [ 4.,  2.,  5.,  3.,  9.],
       [ 5.,  3.,  7.,  7., 11.]])

In [23]:
# Multiply the ones array with the latest array
latest = (r_a_4 + ones + ones)*ones
latest

array([[ 6.,  3.,  5.,  8.,  9.],
       [ 4.,  2.,  5.,  3.,  9.],
       [ 5.,  3.,  7.,  7., 11.]])

In [24]:
# Take the latest array to the power of 2 using '**'
latest**2

array([[ 36.,   9.,  25.,  64.,  81.],
       [ 16.,   4.,  25.,   9.,  81.],
       [ 25.,   9.,  49.,  49., 121.]])

In [25]:
# Do the same thing with np.square()
np.square(latest)

array([[ 36.,   9.,  25.,  64.,  81.],
       [ 16.,   4.,  25.,   9.,  81.],
       [ 25.,   9.,  49.,  49., 121.]])

In [26]:
# Find the mean of the latest array using np.mean()
np.mean(latest)

np.float64(5.8)

In [27]:
# Find the maximum of the latest array using np.max()
latest, np.max(latest)

(array([[ 6.,  3.,  5.,  8.,  9.],
        [ 4.,  2.,  5.,  3.,  9.],
        [ 5.,  3.,  7.,  7., 11.]]),
 np.float64(11.0))

In [28]:
# Find the minimum of the latest array using np.min()
np.min(latest)

np.float64(2.0)

In [29]:
# Find the standard deviation of the latest array
std = np.std(latest)
std, std**2 #std**2=var

(np.float64(2.5612496949731396), np.float64(6.5600000000000005))

In [30]:
# Find the variance of the latest array
var = np.var(latest)
var

np.float64(6.5600000000000005)

In [31]:
latest


array([[ 6.,  3.,  5.,  8.,  9.],
       [ 4.,  2.,  5.,  3.,  9.],
       [ 5.,  3.,  7.,  7., 11.]])

In [32]:
# Reshape the latest array to (3, 5, 1)
latest = latest.reshape(3,5,1)
latest

array([[[ 6.],
        [ 3.],
        [ 5.],
        [ 8.],
        [ 9.]],

       [[ 4.],
        [ 2.],
        [ 5.],
        [ 3.],
        [ 9.]],

       [[ 5.],
        [ 3.],
        [ 7.],
        [ 7.],
        [11.]]])

In [33]:
# Transpose the latest array
latest.T

array([[[ 6.,  4.,  5.],
        [ 3.,  2.,  3.],
        [ 5.,  5.,  7.],
        [ 8.,  3.,  7.],
        [ 9.,  9., 11.]]])

In [57]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
first_arr = np.random.randint(0,10, (3,3))
second_arr = np.random.randint(0,10, (3,2))
first_arr, second_arr

(array([[8, 7, 4],
        [1, 4, 7],
        [9, 8, 8]], dtype=int32),
 array([[0, 8],
        [6, 8],
        [7, 0]], dtype=int32))

In [58]:
# Perform a dot product on the two newest arrays you created
np.dot(first_arr, second_arr)

array([[ 70, 120],
       [ 73,  40],
       [104, 136]], dtype=int32)

In [59]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a = np.random.randint(0,10, (4,3))
b = np.random.randint(0,10, (4,3))
a,b

(array([[7, 7, 2],
        [0, 7, 2],
        [2, 0, 4],
        [9, 6, 9]], dtype=int32),
 array([[8, 6, 8],
        [7, 1, 0],
        [6, 6, 7],
        [4, 2, 7]], dtype=int32))

In [63]:
# Perform a dot product on the two newest arrays you created
b = b.reshape(3,4) #or b.T
np.dot(a,b)

array([[ 77,  50, 102, 105],
       [ 21,   8,  46,  56],
       [ 44,  28,  24,  42],
       [141,  90, 126, 162]], dtype=int32)

In [68]:
# Compare the two arrays with '>'
a.T > b

array([[False, False, False,  True],
       [ True,  True, False, False],
       [False, False,  True,  True]])

In [69]:
# Compare the two arrays with '>='
a.T >= b

array([[False, False, False,  True],
       [ True,  True, False,  True],
       [False, False,  True,  True]])

In [70]:
# Find which elements of the first array are greater than 7
b > 7

array([[ True, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [71]:
# Which parts of each array are equal? (try using '==')
a.T == b

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False]])

In [73]:
# Sort one of the arrays you just created in ascending order
np.sort(a)

array([[0, 0, 2],
       [2, 2, 6],
       [4, 7, 7],
       [7, 9, 9]], dtype=int32)

In [80]:
# Sort the indexes of one of the arrays you just created
np.argsort(a)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [82]:
# Find the index with the maximum value in one of the arrays you've created
a, np.argmax(a), np.argmax(a, axis=0), np.argmax(a, axis=1)

(array([[0, 0, 2],
        [2, 2, 6],
        [4, 7, 7],
        [7, 9, 9]], dtype=int32),
 np.int64(10),
 array([3, 3, 3]),
 array([2, 2, 1, 1]))

In [81]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a, axis=0), np.argmin(a, axis=1)

(array([0, 0, 0]), array([0, 0, 0, 0]))

In [83]:
# Create an array of normally distributed random numbers
np.random.rand(3,5)

array([[0.27472179, 0.56124343, 0.38292687, 0.9717121 , 0.84891382],
       [0.72172952, 0.23598492, 0.25606832, 0.04043359, 0.71066289],
       [0.11089082, 0.4393365 , 0.2017192 , 0.8957636 , 0.47537022]])

In [85]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10), np.arange(1,100,10)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]),
 array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]))

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.